[package]
name = "serial-monitor-rust"
version = "0.1.1"
edition = "2021"
authors = ["Linus Leo Stöckli"]
description = "Serial Monitor and Plotter written in rust."
license = "GPL-3.0"
homepage = "https://github.com/hacknus/serial-monitor-rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { git = "https://github.com/emilk/egui", features = ["persistence"] }
egui_extras = { version = "0.21.0", features = ["image"] }
image = { version = "0.24", default-features = false, features = ["png"] }
rand = "0.8.4"
itertools-num = "0.1"
realfft = "3.0.0"
rfd = "0.11.0"
hex = "0.4"
safe-transmute = "0.11.2"
preferences = { git = "https://github.com/andybarron/preferences-rs" }
serde = { version = "1.0", features = ["derive"] }
regex = "1"
csv = "1.1.6"
serialport = "4.2.0"
keepawake = { git = "https://github.com/segevfiner/keepawake-rs" }

[package.metadata.bundle]
name = "Serial Monitor"
identifier = "com.hacknus.serial_monitor"
icon = ["./icons/install.png"]
version = "0.1.1"
copyright = "Copyright (c) hacknus 2023. All rights reserved."
category = "Developer Tool"
short_description = "Serial Monitor and Plotter written in rust."
license = "GPL-3.0"
osx_minimum_system_version = "10.8"
osx_url_schemes = ["com.hacknus.serial_monitor"]

[package.metadata.wix]
dbg-build = false
dbg-name = false
name = "Serial Monitor"
no-build = false
output = "target/wix/SerialMonitorInstaller.msi"
version = "0.1.1"
license = "GPL-3.0"